import {
  Trip,
  TripStatus,
  Reservation,
  ReservationStatus,
  UserProfile,
  QuickStat,
  UpcomingService,
  StopInfo,
  WeatherInfo,
  LatestNotification,
  Notification,
} from '@/types/passenger';
import { colors } from '@/theme';

export const userProfile: UserProfile = {
  id: 'u1',
  name: 'Ahmet Yılmaz',
  initials: 'AY',
  email: 'ahmet.yilmaz@sirket.com',
  phone: '+90 532 XXX XX XX',
  department: 'Yazılım Geliştirme',
  memberSince: '2024-03-15',
  totalTrips: 47,
  rating: 4.8,
};

export const trips: Trip[] = [
  {
    id: 't1',
    from: 'İstanbul',
    to: 'Ankara',
    date: '2025-02-18',
    time: '08:00',
    status: TripStatus.Upcoming,
    driverName: 'Mehmet K.',
    driverRating: 4.9,
    price: 450,
    vehiclePlate: '34 ABC 123',
  },
  {
    id: 't2',
    from: 'Ankara',
    to: 'İzmir',
    date: '2025-02-20',
    time: '10:30',
    status: TripStatus.Upcoming,
    driverName: 'Ali D.',
    driverRating: 4.7,
    price: 520,
    vehiclePlate: '06 DEF 456',
  },
  {
    id: 't3',
    from: 'İstanbul',
    to: 'Bursa',
    date: '2025-02-15',
    time: '14:00',
    status: TripStatus.InProgress,
    driverName: 'Hasan T.',
    driverRating: 4.8,
    price: 200,
    vehiclePlate: '34 GHI 789',
  },
  {
    id: 't4',
    from: 'İzmir',
    to: 'Antalya',
    date: '2025-02-10',
    time: '09:00',
    status: TripStatus.Completed,
    driverName: 'Yusuf A.',
    driverRating: 4.6,
    price: 380,
    vehiclePlate: '35 JKL 012',
  },
  {
    id: 't5',
    from: 'Ankara',
    to: 'İstanbul',
    date: '2025-02-08',
    time: '16:00',
    status: TripStatus.Completed,
    driverName: 'Emre S.',
    driverRating: 4.9,
    price: 460,
    vehiclePlate: '06 MNO 345',
  },
  {
    id: 't6',
    from: 'İstanbul',
    to: 'Eskişehir',
    date: '2025-02-05',
    time: '07:30',
    status: TripStatus.Completed,
    driverName: 'Burak Ö.',
    driverRating: 4.5,
    price: 280,
    vehiclePlate: '34 PQR 678',
  },
  {
    id: 't7',
    from: 'Bursa',
    to: 'İstanbul',
    date: '2025-02-03',
    time: '18:00',
    status: TripStatus.Cancelled,
    driverName: 'Okan Y.',
    driverRating: 4.7,
    price: 210,
    vehiclePlate: '16 STU 901',
  },
  {
    id: 't8',
    from: 'Antalya',
    to: 'İstanbul',
    date: '2025-02-22',
    time: '06:00',
    status: TripStatus.Upcoming,
    driverName: 'Serkan B.',
    driverRating: 4.8,
    price: 650,
    vehiclePlate: '07 VWX 234',
  },
  {
    id: 't9',
    from: 'İstanbul',
    to: 'Trabzon',
    date: '2025-01-28',
    time: '11:00',
    status: TripStatus.Completed,
    driverName: 'Kemal R.',
    driverRating: 4.4,
    price: 580,
    vehiclePlate: '34 YZA 567',
  },
  {
    id: 't10',
    from: 'İzmir',
    to: 'İstanbul',
    date: '2025-01-25',
    time: '13:30',
    status: TripStatus.Completed,
    driverName: 'Cenk M.',
    driverRating: 4.6,
    price: 500,
    vehiclePlate: '35 BCD 890',
  },
];

export const reservations: Reservation[] = [
  {
    id: 'r1',
    referenceNo: 'SS-2025-001',
    tripId: 't1',
    status: ReservationStatus.Confirmed,
    createdAt: '2025-02-12',
    seatCount: 1,
  },
  {
    id: 'r2',
    referenceNo: 'SS-2025-002',
    tripId: 't2',
    status: ReservationStatus.Confirmed,
    createdAt: '2025-02-13',
    seatCount: 2,
  },
  {
    id: 'r3',
    referenceNo: 'SS-2025-003',
    tripId: 't8',
    status: ReservationStatus.Pending,
    createdAt: '2025-02-14',
    seatCount: 1,
  },
  {
    id: 'r4',
    referenceNo: 'SS-2025-004',
    tripId: 't4',
    status: ReservationStatus.Confirmed,
    createdAt: '2025-02-01',
    seatCount: 1,
  },
  {
    id: 'r5',
    referenceNo: 'SS-2025-005',
    tripId: 't7',
    status: ReservationStatus.Cancelled,
    createdAt: '2025-01-30',
    seatCount: 1,
  },
  {
    id: 'r6',
    referenceNo: 'SS-2025-006',
    tripId: 't5',
    status: ReservationStatus.Confirmed,
    createdAt: '2025-02-05',
    seatCount: 3,
  },
];

export const quickStats: QuickStat[] = [
  {
    label: 'Total Trips',
    value: '47',
    icon: 'car-outline',
    color: colors.primary,
  },
  {
    label: 'Active Bookings',
    value: '3',
    icon: 'ticket-outline',
    color: colors.success,
  },
  {
    label: 'Upcoming',
    value: '3',
    icon: 'time-outline',
    color: colors.accent,
  },
];

export const upcomingService: UpcomingService = {
  id: 'us1',
  status: 'active',
  statusLabel: 'Aktif - Yolda',
  countdownMinutes: 22,
  progress: 0.65,
  routeFrom: 'Kadıköy Rıhtım',
  routeTo: 'Teknopark',
  departureTime: '07:45',
  stopName: 'Kadıköy Rıhtım',
  vehiclePlate: '34 DSY 26',
  driverName: 'Mehmet Yılmaz',
  driverInitials: 'MY',
  driverRole: 'Şoför',
  driverRating: 4.8,
};

export const stopInfo: StopInfo = {
  name: 'Kadıköy Rıhtım',
  distanceText: '350 m uzaklıkta',
};

export const weatherInfo: WeatherInfo = {
  city: 'İstanbul',
  temperature: '8°C',
  condition: 'Parçalı Bulutlu',
};

export const latestNotification: LatestNotification = {
  title: 'Servisiniz yola çıktı!',
  subtitle: 'Tahmini varış: 07:23 - Kadıköy Rıhtım durağı',
  timeAgo: '2 dk önce',
};

export const notifications: Notification[] = [
  {
    id: 'n1',
    title: 'Servis 5 dakika içinde durağınızda',
    body: 'Kadıköy Rıhtım durağınıza yaklaşıyor.',
    type: 'info',
    timeAgo: '2 dk önce',
    read: false,
    group: 'today',
  },
  {
    id: 'n2',
    title: 'Güzergâh değişikliği yapıldı',
    body: 'Yeni güzergâh haritada güncellendi.',
    type: 'warning',
    timeAgo: '1 saat önce',
    read: false,
    group: 'today',
  },
  {
    id: 'n3',
    title: 'Yarın servis saati 07:30 olarak güncellendi',
    body: '11 Şubat Salı günü geçerlidir.',
    type: 'info',
    timeAgo: '3 saat önce',
    read: false,
    group: 'today',
  },
  {
    id: 'n4',
    title: 'Aylık servis raporunuz hazır',
    body: 'Ocak 2026 raporunu görüntüleyebilirsiniz.',
    type: 'success',
    timeAgo: '1 gün önce',
    read: true,
    group: 'earlier',
  },
  {
    id: 'n5',
    title: 'Servis durağınıza ulaştı',
    body: 'Kadıköy Rıhtım durağında bekliyor.',
    type: 'info',
    timeAgo: '2 gün önce',
    read: true,
    group: 'earlier',
  },
];

export function getTripForReservation(reservation: Reservation): Trip | undefined {
  return trips.find((t) => t.id === reservation.tripId);
}
